config/routes.rb
Rails.application.routes.draw do
  resources :edges
  root 'boards#index'

  resources :cards
  resources :groups
  resources :boards
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :cards do
    put 'cards/:id/move/' => 'cards#set_group', as: 'set_group'

    put 'cards/:id/order/' => 'cards#set_order', as: 'set_order'

  end

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  controller :boards do
    get 'boards/:id/add-user/' => 'boards#add_user', as: 'new_board_user'
    post 'boards/:id/add-user/' => 'boards#add_user', as: 'add_board_user'
    delete 'boards/:id/users/:user_id/destroy' => 'boards#remove_user', as: 'remove_board_user'
    get 'boards/:id/manage/' => 'boards#manage', as: 'manage_board'
  end

  controller :card_user do

    get 'cards/:id/users/' => 'card_user#show', as: 'show_card_user'
    get 'cards/:id/users/create' => 'card_user#new', as: 'new_card_user'
    post 'cards/:id/users/create' => 'card_user#create', as: 'create_card_user'
    delete 'cards/:id/users/:user_id/destroy' => 'card_user#destroy', as: 'destroy_card_user'
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :board
  has_many :cards

  validates :board, presence: true

  def to_s
    (name || 'group ') + id.to_s
  end

  def user_have_permission_to_view(user)
    board.user_have_permission_to_view(user)
  end

  def get_cards(user)
    if board.user == user
      cards
    elsif board.users.include? user
      board_permission = user.permissions.where(board_id: board).distinct.first

      if board_permission && board_permission.to_card_only
        cards.joins(:users).where("cards_users.user_id = #{user.id}").distinct.order(:order)
      else
        cards.order(:order)
      end
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group.board, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group.board, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :board_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
    <% if @group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

          <ul>
            <% @group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% if @group.id %>
      <%= f.hidden_field :board_id %>
    <% else %>
      <%= f.hidden_field :board_id, value: params[:board_id] %>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
    </div>

    <%= f.button type: 'submit', class: 'btn btn-default' %>
<% end %>

app/views/groups/_group.html.erb
<div id="group-<%= group.id %>" class="group" data-group-id="<%= group.id %>">
  <div class="group-menu">
    <%= link_to new_card_path(group_id: group.id), remote: true  do %>
        <span class="glyphicon glyphicon-plus"></span> New Card
    <% end %>

    <%= link_to edit_group_path(group)do %>
        <span class="glyphicon glyphicon-edit"></span> Edit
    <% end %>
  </div>

  <div class="group-heading">
    <%= link_to group.name, group_path(group) %>
  </div>

  <div class="group-body">
    <ul class="cards list-unstyled">
      <% group.get_cards(@current_user).each do |card| %>
          <li id="card-<%= card.id %>" class="card" data-card-id="<%= card.id %>">
            <%= render partial: 'cards/smallcard', object: card, as: "card" %>
          </li>
      <% end %>
    </ul>
  </div>
</div>

<%= render 'cards/dialog' %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Board</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.board %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @group %>