config/routes.rb
Rails.application.routes.draw do
  resources :edges
  root 'boards#index'

  resources :cards
  resources :groups
  resources :boards
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :cards do
    put 'cards/:id/move/' => 'cards#set_group', as: 'set_group'

    put 'cards/:id/order/' => 'cards#set_order', as: 'set_order'

  end

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  controller :boards do
    get 'boards/:id/add-user/' => 'boards#add_user', as: 'new_board_user'
    post 'boards/:id/add-user/' => 'boards#add_user', as: 'add_board_user'
    delete 'boards/:id/users/:user_id/destroy' => 'boards#remove_user', as: 'remove_board_user'
    get 'boards/:id/manage/' => 'boards#manage', as: 'manage_board'
  end

  controller :card_user do

    get 'cards/:id/users/' => 'card_user#show', as: 'show_card_user'
    get 'cards/:id/users/create' => 'card_user#new', as: 'new_card_user'
    post 'cards/:id/users/create' => 'card_user#create', as: 'create_card_user'
    delete 'cards/:id/users/:user_id/destroy' => 'card_user#destroy', as: 'destroy_card_user'
  end

end

app/models/edge.rb
class Edge < ActiveRecord::Base
  belongs_to :card_a, class_name: 'Card', foreign_key: :card_a_id
  belongs_to :card_b, class_name: 'Card', foreign_key: :card_b_id

  validates :card_a_id, :card_b_id, :relation, presence: true, on: :create
  validate :has_cards, on: :create
  validate :only_one_parent, on: :create
  validates_uniqueness_of :card_a_id, scope: [:card_b_id, :relation]

  def get_related_to(card)
    if card == card_a
      card_b
    elsif card == card_b
      card_a
    end
  end

  private

    def has_cards
      errors.add(:card_a_id, "card doesn't exist") unless Card.exists? card_a_id
      errors.add(:card_b_id, "card doesn't exist") unless Card.exists? card_b_id
    end

    def only_one_parent
      if relation == EdgesController.helpers.parent
        if Edge.exists?(card_b_id: card_b_id, relation: relation)
          errors.add(:card_b_id, "card #{card_b} already have parent")
        end

        if Edge.exists?(card_a_id: card_b_id, card_b_id: card_a_id, relation: relation)
          errors.add(:card_a_id, " [#{card_a}] can't have as child self parent [#{card_b}]")
        end

        if card_a_id == card_b_id
          errors.add(:card_a_id, 'card can be self parent')
          errors.add(:card_b_id, 'card can be self parent')
        end
      end

    end

end

app/controllers/edges_controller.rb
class EdgesController < ApplicationController
  before_action :set_edge, only: [:show, :edit, :update, :destroy]

  # GET /edges
  # GET /edges.json
  def index
    @edges = Edge.all
  end

  # GET /edges/1
  # GET /edges/1.json
  def show
  end

  # GET /edges/new
  def new
    @edge = Edge.new(card_a_id: params[:card_a_id], card_b_id: params[:card_b_id], relation: params[:relation])
  end

  # GET /edges/1/edit
  def edit
  end

  # POST /edges
  # POST /edges.json
  def create
    @edge = Edge.new(edge_params)

    respond_to do |format|
      if @edge.save
        format.html { redirect_to @edge, notice: 'Edge was successfully created.' }
        format.json { render :show, status: :created, location: @edge }
      else
        format.html { render :new }
        format.json { render json: @edge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /edges/1
  # PATCH/PUT /edges/1.json
  def update
    respond_to do |format|
      if @edge.update(edge_params)
        format.html { redirect_to @edge, notice: 'Edge was successfully updated.' }
        format.json { render :show, status: :ok, location: @edge }
      else
        format.html { render :edit }
        format.json { render json: @edge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edges/1
  # DELETE /edges/1.json
  def destroy
    @edge.destroy
    respond_to do |format|
      format.html { redirect_to edges_url, notice: 'Edge was successfully destroyed.' }
      format.js { render 'deleted' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edge
      @edge = Edge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edge_params
      params.require(:edge).permit(:card_a_id, :card_b_id, :relation)
    end
end

app/helpers/edges_helper.rb
module EdgesHelper
  def undirected
    0
  end
  def parent
    1
  end
  def directed
    2
  end

  def edge_relation_str(relation)
    %w(undirected parent directed)[relation]
  end

end

app/views/edges/_form.html.erb
<%= form_for(@edge) do |f| %>
  <% if @edge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edge.errors.count, "error") %> prohibited this edge from being saved:</h2>

      <ul>
      <% @edge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :card_a_id %><br>
    <%= f.text_field :card_a_id %>
  </div>
  <div class="field">
    <%= f.label :card_b_id %><br>
    <%= f.text_field :card_b_id %>
  </div>
  <div class="field">
    <%= f.label :relation %><br>
    <%= f.number_field :relation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/edges/deleted.js.erb
$("#edge-<%= @edge.id %>").remove();

app/views/edges/edit.html.erb
<h1>Editing Edge</h1>

<%= render 'form' %>

<%= link_to 'Show', @edge %> |
<%= link_to 'Back', edges_path %>

app/views/edges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Edges</h1>

<table class="table">
  <thead>
    <tr>
      <th>Card a</th>
      <th>Card b</th>
      <th>Relation</th>
      <th>Opperation</th>
    </tr>
  </thead>

  <tbody>
    <% @edges.each do |edge| %>
      <tr>
        <td><%= edge.card_a %></td>
        <td><%= edge.card_b %></td>
        <td><%= edge_relation_str edge.relation %></td>
        <td>
          <%= link_to 'Show', edge %> |
          <%= link_to 'Edit', edit_edge_path(edge) %> |
          <%= link_to 'Destroy', edge, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Edge', new_edge_path %>

app/views/edges/new.html.erb
<h1>New Edge</h1>

<%= render 'form' %>

<%= link_to 'Back', edges_path %>

app/views/edges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Card a:</strong>
  <%= @edge.card_a %>
</p>

<p>
  <strong>Card b:</strong>
  <%= @edge.card_b %>
</p>

<p>
  <strong>Relation:</strong>
  <%= @edge.relation %>
</p>

<%= link_to 'Edit', edit_edge_path(@edge) %> |
<%= link_to 'Back', edges_path %>