config/routes.rb
Rails.application.routes.draw do
  resources :edges
  root 'boards#index'

  resources :cards
  resources :groups
  resources :boards
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :cards do
    put 'cards/:id/move/' => 'cards#set_group', as: 'set_group'

    put 'cards/:id/order/' => 'cards#set_order', as: 'set_order'

  end

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  controller :boards do
    get 'boards/:id/add-user/' => 'boards#add_user', as: 'new_board_user'
    post 'boards/:id/add-user/' => 'boards#add_user', as: 'add_board_user'
    delete 'boards/:id/users/:user_id/destroy' => 'boards#remove_user', as: 'remove_board_user'
    get 'boards/:id/manage/' => 'boards#manage', as: 'manage_board'
  end

  controller :card_user do

    get 'cards/:id/users/' => 'card_user#show', as: 'show_card_user'
    get 'cards/:id/users/create' => 'card_user#new', as: 'new_card_user'
    post 'cards/:id/users/create' => 'card_user#create', as: 'create_card_user'
    delete 'cards/:id/users/:user_id/destroy' => 'card_user#destroy', as: 'destroy_card_user'
  end

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :permissions
  has_many :users, through: :permissions
  has_many :groups

  validates :name, :user, presence: true

  def to_s
    name
  end

  def user_have_permission_to_view(u)
    user == u || users.include?(u)
  end

  def user_can_manage(current_user)
    permission = users.include?(current_user) ? permissions.where(user_id: current_user).distinct.first : nil

    (user == current_user) || permission && permission.to_edit
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy, :add_user, :remove_user, :manage]
  before_action :set_user, only: [:remove_user]
  before_action :check_can_manage, only: [:manage, :add_user, :remove_user]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.where(user:@current_user).order(:name)
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    session[:board_id] = @board.id
  end

  # GET /boards/new
  def new
    @board = Board.new(user: @current_user)
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /boards/1/add-user
  # POST /boards/1/add-user.json
  def add_user
    user = User.find_by(email: permission_params[:email])
    if user
      if @board.users.include? user
        respond_to do |format|
          format.html { redirect_to manage_board_path(@board), notice: "User #{user} already was added to board #{@board}"}
          format.json { head :no_content }
        end

      else
        puts 'permission_params-', params, permission_params
        @permission = Permission.new(board: @board, user: user, permission: permission_params['permission'])
        if @permission.save
          respond_to do |format|
            format.html { redirect_to manage_board_path(@board), notice: "User #{user} was successfully added to board #{@board}"}
            format.json { render json: user, status: :ok }
          end
        end

      end
    else
      respond_to do |format|
        format.html {redirect_to manage_board_path(@board)}
      end
    end
  end

  # DELETE /boards/1/remove-user
  # DELETE /boards/1/remove-user.json
  def remove_user
    @board.users.delete(@user)
    respond_to do |format|
      format.html { manage_board_path @board, notice: "User #{ user } was successfully deleted from board #{@board}." }
      format.js { render :remove_user }
      format.json { head :no_content }
    end
  end

  # GET /boards/:id/manage/
  def manage
     @permission = Permission.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :user_id)
    end

    def permission_params
      params.require(:permission).permit(:email, :permission)
    end

    def check_can_manage
      unless @board.user_can_manage(@current_user)
        redirect_to root_path
      end
    end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_available_board.html.erb
<%= link_to board, class: 'board-name' do %>
    <span class="glyphicon glyphicon-cloud"></span>
    <%= board.name %>
<% end %>

app/views/boards/_board.html.erb
<li class="board">
  <% if is_mine %>
    <%= render partial: 'my_board', object: board, as: :board %>
  <% else %>
    <%= render partial: 'available_board', object: board, as: :board %>
  <% end %>
  <div class="board-action-panel">
    <% if board.user_can_manage @current_user %>
      <%= link_to manage_board_path(board),  class: 'board-manage btn btn-default' do %>
          <span class="glyphicon glyphicon-cog"></span>
      <% end %>

      <%= link_to edit_board_path(board),  class: 'board-edit btn btn-default' do %>
          <span class="glyphicon glyphicon-edit"></span>
      <% end %>


      <%= link_to board, method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    <% end %>
  </div>
</li>

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/_my_board.html.erb
<%= link_to board, class: 'board-name' do %>
    <span class="glyphicon glyphicon-ok-sign"></span>
    <%= board.name %>
<% end %>

app/views/boards/_user.html.erb
<li id="board-user-<%= permission.user.id %>" class="user list-group-item">
  <%= link_to remove_board_user_path(board, user_id:permission.user), method: :delete, data: {confirm: 'Are you sure?' }, class:'remove-user', remote:true do %>
      <span class="glyphicon glyphicon-remove-sign"></span>
  <% end %>

  <%= permission.user %>
  <span class="label label-info"><%= permission_to_s permission.permission %></span>
</li>

app/views/boards/add_user.html.erb
<%= render 'permission/form' %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>

<%= link_to new_board_path do  %>
  <span class="glyphicon glyphicon-plus"></span> New Board
<% end %>

<ul id="boards-list" class="list-unstyled">
  <%= render partial: 'board', collection: @boards, locals: {is_mine: true} %>
  <%= render partial: 'board', collection: @current_user.available_boards, locals: {is_mine: false} %>
</ul>

app/views/boards/manage.html.erb
<%= render 'permission/form' %>
<div class="col-md-8">
  <% if @board.users.any? %>
        available to:
      <ul class="list-group">
        <%= render partial: 'user', collection: @board.permissions, as: 'permission', locals: {board: @board} %>
      </ul>
  <% end %>
</div>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/remove_user.js.erb
$("#board-user-<%= @user.id %>").remove();

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<div id="board">
<div class="board-header">
  <h1 class="board-name">
    <%= link_to @board.name, edit_board_path(@board) %>

  </h1>

  <ul class="nav nav-pills">
    <% if @board.user_can_manage @current_user %>
      <li role="presentation">
        <%= link_to manage_board_path(@board),  class: 'board-manage btn btn-default' do %>
            <span class="glyphicon glyphicon-cog"></span> Settings
        <% end %>
      </li>
    <% end %>

    <li role="presentation">
      <%= link_to new_group_path(board_id: @board.id), class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-plus"></span> New Group
      <% end %>
    </li>
  </ul>
</div>
  <%= render partial: 'groups/group', collection: @board.groups  %>

  <%= render 'cards/dialog' %>
</div>