config/routes.rb
Rails.application.routes.draw do
  resources :edges
  root 'boards#index'

  resources :cards
  resources :groups
  resources :boards
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :cards do
    put 'cards/:id/move/' => 'cards#set_group', as: 'set_group'

    put 'cards/:id/order/' => 'cards#set_order', as: 'set_order'

  end

  resources :comments, only: [:index, :create]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment

  controller :boards do
    get 'boards/:id/add-user/' => 'boards#add_user', as: 'new_board_user'
    post 'boards/:id/add-user/' => 'boards#add_user', as: 'add_board_user'
    delete 'boards/:id/users/:user_id/destroy' => 'boards#remove_user', as: 'remove_board_user'
    get 'boards/:id/manage/' => 'boards#manage', as: 'manage_board'
  end

  controller :card_user do

    get 'cards/:id/users/' => 'card_user#show', as: 'show_card_user'
    get 'cards/:id/users/create' => 'card_user#new', as: 'new_card_user'
    post 'cards/:id/users/create' => 'card_user#create', as: 'create_card_user'
    delete 'cards/:id/users/:user_id/destroy' => 'card_user#destroy', as: 'destroy_card_user'
  end

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :group
  has_many :comments
  has_many :a_edges, class_name: 'Edge', foreign_key: :card_a_id
  has_many :b_edges, class_name: 'Edge', foreign_key: :card_b_id
  has_and_belongs_to_many :users

  def to_s
    title
  end

  def parent
    Card.joins(:a_edges).where("edges.card_b_id = #{id} and edges.relation = #{ EdgesController.helpers.parent } and cards.id != #{id}").first
  end

  def related_cards
    unless @related
      @related = edges_to_hash(a_edges)
      undirected_from_b_side = edges_to_hash(b_edges.where("edges.relation = #{ EdgesController.helpers.undirected }"))
      @related['undirected'] = @related['undirected'] || []
      @related['undirected'] += (undirected_from_b_side['undirected']) || []
    end
    @related
  end

  def edges_to_hash(edges)
    related = {}
    relations = %w(undirected children directed)
    edges.each do |edge|
      relation = relations[edge.relation]
      unless related.has_key? relation
        related[relation] = []
      end
      related[relation].append([edge.get_related_to(self), edge])
    end
    related

  end


  def children
    Card.joins(:a_edges).where("edges.relation = #{ EdgesController.helpers.parent }")
  end

  def count_relatives
    counter = 0
    related_cards.each do |type, relatives|
      counter += relatives.length
    end
    counter
  end

  def user_have_permission_to_view(user)
    group.board.user_have_permission_to_view user
  end

  def user_can_manage(current_user)
    group.board.user_can_manage(current_user) || users.include?(current_user)
  end




  def self.search(search, user)
    if search
      own_cards = joins(:group => :board).where("text LIKE '%#{search}%' and boards.user_id = #{user.id}").pluck(:id)
      shered_cards = joins(:group => [:board, {board: :users}]).where("text LIKE '%#{search}%' and #{user.id} or users.id = #{user.id}").pluck(:id)

      Card.where(id: own_cards | shered_cards).order(:title)
    else
      find(:all).joins(:group => :board).where("boards.user_id = #{user.id}").order_by(:title)
    end
  end



end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy, :set_group, :set_order]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.search(params[:search], @current_user)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        if parent
          edge = Edge.new(card_a: parent, card_b: @card, relation: 1)
          puts 'edge ', edge.save, edge.id
        end
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.js { render 'created', status: :created  }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.js { render 'updated', status: :created  }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.js {render :deleted}
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def set_group
    @card.group = Group.find(params[:group_id])
    respond_to do |format|
      if @card.save
        format.html { redirect_to board_url(Group.find(params[:group_id]).board), notice: 'Card was successfully moved'}
        format.json { head :no_content }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def set_order
    data = params[:data]
    data.each { |key, value|
      card = Card.find(key)
      card.order = value
      card.save
    }
    respond_to do |format|
      format.html { redirect_to board_url(@card.group.board), notice: 'Card was successfully moved'}
      format.json {head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      c_params = params.require(:card).permit(:text, :group_id, :start_date, :due_date)
      text = c_params[:text]
      lines = text.lines
      title = lines.shift || 'Title'

      html = Kramdown::Document.new(lines.join).to_html

      group = Group.find(c_params[:group_id])


      c_params.merge({text: text, html: html, group: group, title: title})
    end

    def parent
      p = params.require(:card).permit(:parent_id)
      unless p[:parent_id].blank?
        Card.find p[:parent_id]
      end
    end


end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div class="card-body">
  <div>
    <% parent = card.parent  %>
    <% if parent %>
        <div id="parent">
          Parent: <%= link_to parent.title , card_path(parent), remote: true %>
        </div>
    <% end %>


  <div class="card-info">
    <% if card.start_date || card.due_date %>
      <div>
        <% if card.start_date %>
            <span class="label label-default">Start date: <%= card.start_date %></span>
        <% end %>

        <% if card.due_date %>
            <span class="label label-default">Due date: <%= card.due_date %></span>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= card.html.html_safe %>

  <%= render partial:'relatives', object: card.related_cards, as: 'relatives' %>

  </div>

</div>
<% if card.group.board.users.any? %>
  <%= render partial:'card_user/users', object: card, as: 'card' %>
<% end %>

<div class="comments">
  <%= link_to 'Add new comment', new_comment_path(card_id:@card.id), class: 'btn btn-primary add-new-comment', remote: true  %>

  <%= comments_tree_for @card.comments.hash_tree %>
</div>

app/views/cards/_cardtitle.html.erb
<%= link_to edit_card_path(card), class: 'link-help-container' do %>
    <h1><%= card.title %></h1>
    <span class="link-help">
      <span class="glyphicon glyphicon-edit"></span>
    </span>
<% end %>

app/views/cards/_dialog.html.erb
<div id="card-dialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="modal-title card-title"></div>
      </div>
      <div class="modal-body"></div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>

    <%= f.hidden_field :parent_id, value:params[:parent_id] %>

    <% if @card.id %>
        <%= f.hidden_field :group_id %>
    <% else %>
        <%= f.hidden_field :group_id, value: params[:group_id] %>
    <% end %>

    <div class="form-group">
      <%= f.label :text, class: 'sr-only' %><br>
      <%= f.text_area :text, class: 'form-control card-text', rows: '20' %>
    </div>

    <div class="form-group">
      <div class='input-group date' id='datetimepicker-start-date'>
        <%= f.text_field :start_date, class: 'form-control' %>
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
    </div>

    <div class="form-group">
      <div class='input-group date' id='datetimepicker-due-date'>
        <%= f.text_field :due_date, class: 'form-control' %>
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
    </div>

    <div class="form-group">
      <%= f.button  'OK', type: 'submit', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/cards/_relatives.html.erb
<% unless relatives.empty? %>
    <% relatives.each do |relation, cards| %>
        <% if cards.any? %>
          <%= relation %>
          <ul id="linked-to-cards" class="list-unstyled">
            <% cards.each do |card, edge| %>
                <li id="edge-<%= edge.id %>">
                  <%= link_to card.title , card_path(card), remote: true %>
                  <%= link_to edge, method: :delete, data: { confirm: 'Are you sure?' }, remote: true do %>
                      <span class="glyphicon glyphicon-trash"></span> Delete
                  <% end %>
                </li>
            <% end %>
          </ul>
        <% end %>
    <% end %>
<% end %>

app/views/cards/_smallcard.html.erb
<div class="card-content">
  <div class="card-heading">
    <%= link_to card.title, card_path(card), remote: true %>
  </div>


  <div class="card-info">

    <div class="card-body">
      <%= truncate(card.html, length: 100, escape: false) %>
    </div>

    <div>

      <% parent = card.parent %>
      <% if parent %>
          <span class="parent">
            Child of:
            <%= link_to parent.title, card_path(parent), remote: true %>
          </span> |
      <% end %>

      <% show_class = card.count_relatives == 0 ? 'sr-only' : '' %>
      <span class="relatives-info <%= show_class %>">
        <span class="glyphicon glyphicon-link"></span>
        <span class="card-link-length"><%= card.count_relatives %></span>
      </span>
    </div>


  </div>

  <div class="relation-operations">
    <%= link_to new_card_path(parent_id: card, group_id: card.group.id), remote: true do %>
        <span class="glyphicon glyphicon-plus" data-toggle="tooltip" data-placement="left" title="Add child"></span>
    <% end %>

    <span class='card-link-to' data-toggle="tooltip" data-placement="left" title="Connect to">
          <span class="glyphicon glyphicon-link"></span>
      </span>
  </div>

  <div class="card-operations">
    <%= link_to edit_card_path(card), remote: true do %>
        <span class="glyphicon glyphicon-pencil" data-toggle="tooltip" data-placement="left" title="Edit "></span>
    <% end %>

    <%= link_to card_path(card) do %>
        <span class="glyphicon glyphicon-open-file" data-toggle="tooltip" data-placement="left" title="Show in new window"></span>
    <% end %>

    <%= link_to card, method: :delete, data: {confirm: 'Are you sure?'}, class: 'delete-card', remote: true do %>
        <span class="glyphicon glyphicon-trash" data-toggle="tooltip" data-placement="left" title="Delete"></span>
    <% end %>
  </div>


</div>

app/views/cards/created.js.erb
$('#group-' + <%= @card.group.id %>)
    .find('.cards')
    .append(
        $('<li class="card list-group-item" data-card-id="<%= @card.id %>">')
            .html("<%= escape_javascript(render(partial: 'cards/smallcard', object: @card, as: 'card')) %>"));

app/views/cards/deleted.js.erb
$("#card-<%= @card.id %>").fadeOut("slow", function(){
  $(this).remove();
});

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/edit.js.erb
$('#card-dialog')
    .find('.modal-title')
    .html("<%= escape_javascript(@card.title) %>").end()
    .find('.modal-body')
    .html("<%= escape_javascript(render 'form') %>").end()
    .dtpicker()
    .set_ajax_submit(function(){
      $('#card-dialog').modal('hide')
    })

    .modal();

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cards</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>User</th>
      <th>Board</th>
      <th>Group</th>
      <th>Start date</th>
      <th>Due date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <% # noinspection RubyResolve
         if card.group.board.user == @current_user %>
          <% icon = 'glyphicon-ok-sign' %>
          <% c = 'active' %>
      <% else %>
          <% icon = 'glyphicon-cloud' %>
          <% c = '' %>
      <% end %>

      <tr class="<%= c %>">
        <td>
          <span class="glyphicon <%= icon %>"></span>
        </td>
        <td><%= link_to card.title, card %></td>
        <td><%= card.group.board.user %></td>
        <td><%= card.group.board %></td>
        <td><%= card.group %></td>
        <td><%= I18n.l(card.start_date, format: '%d %B %Y') if card.start_date %></td>
        <td><%= I18n.l(card.due_date, format: '%d %B %Y') if card.due_date %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.js.erb
$('#card-dialog')
    .find('.modal-title')
    .html("New card").end()
    .find('.modal-body')
    .html("<%= escape_javascript(render 'form') %>").end()
    .dtpicker()
    .set_ajax_submit(function(){
      $('#card-dialog').modal('hide')
    })

    .modal();

app/views/cards/show.html.erb
<% if notice %>
    <div id="notice"><%= notice %></div>
<% end %>

<ol class="breadcrumb">
  <li><%= link_to @card.group.board, board_path(@card.group.board) %></li>
  <li><%= link_to @card.group, group_path(@card.group) %></li>
  <li class="active"><%= @card %></li>
</ol>

<div class="card-show">
  <div class="card-title edit-bar-container">
    <%= render partial: 'cardtitle', locals: { card: @card } %>
  </div>

  <%= render @card %>
  <%= render 'cards/dialog' %>

</div>

app/views/cards/updated.js.erb
$("#card-<%= @card.id %>")
  .html("<%= escape_javascript(render(partial: 'cards/smallcard', object: @card, as: 'card')) %>");